[build]
target = "thumbv7m-none-eabi"
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv7m-none-eabi]
runner = "probe-rs run --protocol SWD --chip STM32F103C6"

[env]
DEFMT_LOG="off"